"""Intent data model and state machine.

Contract (v1.0):

    proposed -> audited -> awaiting_user -> executing -> settled
                   \\                    \\            \\
                    reject                user_declined failed / playbook_broken

L0 (amount <= l0_ceiling): proposed -> audited -> executing -> settled (no user prompt)
L1 (l0_ceiling < amount <= l1_ceiling): proposed -> audited -> awaiting_user -> executing -> settled
L2 (amount > l1_ceiling): broker refuses to advance past 'proposed' until the human signals approval.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any


DEFAULT_TTL_MINUTES = 5


class IntentState(str, Enum):
    PROPOSED = "proposed"
    AUDITED = "audited"
    AWAITING_USER = "awaiting_user"
    EXECUTING = "executing"
    SETTLED = "settled"
    FAILED = "failed"
    USER_DECLINED = "user_declined"
    PLAYBOOK_BROKEN = "playbook_broken"
    REJECTED = "rejected"
    EXPIRED = "expired"


TERMINAL_STATES = {
    IntentState.SETTLED,
    IntentState.FAILED,
    IntentState.USER_DECLINED,
    IntentState.PLAYBOOK_BROKEN,
    IntentState.REJECTED,
    IntentState.EXPIRED,
}


VALID_TRANSITIONS: dict[IntentState, set[IntentState]] = {
    IntentState.PROPOSED: {IntentState.AUDITED, IntentState.REJECTED, IntentState.EXPIRED},
    IntentState.AUDITED: {
        IntentState.EXECUTING,
        IntentState.AWAITING_USER,
        IntentState.EXPIRED,
        # Execution setup (rail selection, chrome attach) can fail before
        # we ever transition to EXECUTING — record that as a direct failure.
        IntentState.FAILED,
    },
    IntentState.AWAITING_USER: {
        IntentState.EXECUTING,
        IntentState.USER_DECLINED,
        IntentState.EXPIRED,
    },
    IntentState.EXECUTING: {
        IntentState.SETTLED,
        IntentState.FAILED,
        IntentState.PLAYBOOK_BROKEN,
        # L0 intents skip awaiting_user and go straight from audited→executing.
        # If the MetaMask popup shows up anyway and the user declines, we still
        # want to record user_declined rather than a generic failure.
        IntentState.USER_DECLINED,
    },
    # terminal
    IntentState.SETTLED: set(),
    IntentState.FAILED: set(),
    IntentState.USER_DECLINED: set(),
    IntentState.PLAYBOOK_BROKEN: set(),
    IntentState.REJECTED: set(),
    IntentState.EXPIRED: set(),
}


class IntentError(Exception):
    pass


class InvalidTransitionError(IntentError):
    pass


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


@dataclass
class Intent:
    """Payload that Claude Code submits to the broker.

    intent_id is generated by the broker on submission, not supplied by the agent.

    rail_hint is a soft suggestion: the agent can indicate "prefer card" or
    "prefer crypto" when the merchant supports multiple rails and the agent
    has a reason (e.g. crypto has settled faster in history). The broker
    honors the hint when compatible with policy and enrolment, else falls
    through to the configured preference order.
    """

    merchant: str
    amount_usd: float
    rationale: str
    estimated_actual_cost_usd: float
    references: list[str] = field(default_factory=list)
    rail_hint: str | None = None  # "card" | "crypto" | "email_link" | "bank_transfer"
    intent_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    issuer_session: str | None = None
    created_at: datetime = field(default_factory=_now)
    expires_at: datetime = field(
        default_factory=lambda: _now() + timedelta(minutes=DEFAULT_TTL_MINUTES)
    )

    def __post_init__(self) -> None:
        if self.amount_usd <= 0:
            raise IntentError(f"amount_usd must be > 0, got {self.amount_usd}")
        if self.estimated_actual_cost_usd <= 0:
            raise IntentError(
                f"estimated_actual_cost_usd must be > 0, got {self.estimated_actual_cost_usd}"
            )
        if not self.merchant:
            raise IntentError("merchant is required")
        if not self.rationale or len(self.rationale) < 10:
            raise IntentError("rationale must be at least 10 chars")
        # amount should generally be >= estimated actual cost; if the agent
        # is asking for LESS than the underlying cost estimate, that's a bug.
        if self.amount_usd < self.estimated_actual_cost_usd * 0.9:
            raise IntentError(
                f"amount_usd ({self.amount_usd}) is suspiciously lower than "
                f"estimated_actual_cost_usd ({self.estimated_actual_cost_usd}). "
                "Usually amount should include a small buffer."
            )

    def is_expired(self, now: datetime | None = None) -> bool:
        current = now or _now()
        return current >= self.expires_at

    def to_json(self) -> str:
        """Serialize for the auditor. Date fields become ISO strings."""
        d = asdict(self)
        d["created_at"] = _iso(self.created_at)
        d["expires_at"] = _iso(self.expires_at)
        return json.dumps(d, ensure_ascii=False, sort_keys=True)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["created_at"] = _iso(self.created_at)
        d["expires_at"] = _iso(self.expires_at)
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Intent:
        """Rehydrate from a dict (e.g. an incoming MCP request or a DB row)."""
        payload = dict(data)
        # Drop intent_id if caller supplied one — broker assigns it.
        # Unless we're rehydrating from ledger (in which case keep it).
        for k in ("created_at", "expires_at"):
            v = payload.get(k)
            if isinstance(v, str):
                payload[k] = datetime.fromisoformat(v.replace("Z", "+00:00"))
        return cls(**payload)


def assert_transition(old: IntentState, new: IntentState) -> None:
    if new not in VALID_TRANSITIONS.get(old, set()):
        raise InvalidTransitionError(f"cannot transition {old.value} -> {new.value}")


def authorization_tier(amount_usd: float, l0_ceiling: float, l1_ceiling: float) -> str:
    """Map an amount to an authorization tier name (L0 / L1 / L2)."""
    if amount_usd <= l0_ceiling:
        return "L0"
    if amount_usd <= l1_ceiling:
        return "L1"
    return "L2"
